// Library entry point for shared modules (services, models, etc.)
pub mod api;
pub mod auth;
pub mod bias;
pub mod canonical_elements;
pub mod cli;
pub mod config;
pub mod database;
pub mod dto;
pub mod error;
pub mod mapping_correction;
pub mod models;
pub mod neo4j;
pub mod pipeline;
pub mod prompt_loader;
pub mod repositories;
pub mod restate_endpoint;
pub mod services;
pub mod state;
