//! Scenario authored-state store (task 1.1).
//!
//! Owns CRUD for the `scenarios` table created by migration
//! `20260626115557_create_scenarios_table.sql` (in `colossus_legal_v2`, the
//! pipeline database). A scenario is a saved **lens** over the case graph: this
//! table stores only its authored *definition* plus the spine columns the system
//! filters and joins on. It holds **no case content** — no quotes, citations, or
//! facts. Those live in the graph and are referenced by `scenario_fact_refs`
//! (task 1.2), not here.
//!
//! ## Why this is `scenario_store`, not a `ScenarioRepository`
//!
//! A `ScenarioRepository` already exists — the task 0.3 Neo4j graph reader
//! (`repositories::scenario_repository`). To avoid colliding with it, this
//! Postgres authored-state code mirrors the house precedent's shape exactly:
//! stateless free functions (like `authored_entities`), not a struct. Mutators
//! take `impl sqlx::PgExecutor<'_>` so a caller can enroll them in a
//! transaction; readers take `&PgPool`.
//!
//! ## Rust Learning: `impl sqlx::PgExecutor<'_>` on mutators
//!
//! Taking `impl PgExecutor<'_>` (rather than `&PgPool`) means the same function
//! works whether the caller passes a `&PgPool` (each call its own
//! auto-committed statement) or a `&mut Transaction` (several calls in one
//! all-or-nothing unit). A `&PgPool` satisfies the bound, so simple call sites
//! pass `&pool` unchanged — the flexibility costs the caller nothing. The read
//! helpers keep `&PgPool` because there is no transaction-composition need on a
//! plain SELECT.

use sqlx::PgPool;

use super::PipelineRepoError;

// ── Record type ──────────────────────────────────────────────────

/// A row from `scenarios`.
///
/// Field names match the columns exactly so `#[derive(sqlx::FromRow)]` maps the
/// row without a manual decoder.
///
/// ## Rust Learning: `TEXT[]` → `Option<Vec<String>>`
///
/// `anchor_allegation_ids` is a nullable Postgres text array. sqlx decodes a
/// SQL array to a `Vec<T>`, and a nullable column to `Option<…>`, so the column
/// type is `Option<Vec<String>>`: `None` for SQL `NULL`, `Some(vec![])` for an
/// empty array, `Some(vec![..])` for a populated one — three distinguishable
/// states (Standing Rule 1).
///
/// ## Why `definition` is `serde_json::Value`, not a typed struct
///
/// The definition body (attack_text, wielders, seed phrases, a `schema_v` tag,
/// …) is the authored part that churns. Modeling it as a Rust struct would force
/// a recompile — and often a migration — on every authoring-format tweak. As
/// raw `serde_json::Value` it absorbs change freely; its shape is validated at
/// render time (task 1.5), not by this store or the table. This mirrors how
/// `authored_entities.item_data` is stored.
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ScenarioRecord {
    pub scenario_id: uuid::Uuid,
    pub name: String,
    pub direction: String,
    pub status: String,
    pub case_slug: String,
    pub feeds_count_id: Option<String>,
    pub anchor_allegation_ids: Option<Vec<String>>,
    pub definition: serde_json::Value,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

/// Shared SELECT projection for every `ScenarioRecord` read, so the `FromRow`
/// column set can never drift between query sites (the house anti-drift
/// discipline; see `authored_entities::ENTITY_COLUMNS`).
// CONST: column projection locked to the `scenarios` schema. This is a
// structural schema-coupling invariant, NOT a deployment-time config value —
// changing it requires a simultaneous migration and a matching `ScenarioRecord`
// field update, so it cannot live in YAML/env (Standing Rule 2 does not apply).
const SCENARIO_COLUMNS: &str = "scenario_id, name, direction, status, case_slug, \
     feeds_count_id, anchor_allegation_ids, definition, created_at, updated_at";

// ── CRUD ─────────────────────────────────────────────────────────

/// Insert a scenario and return its database-minted `scenario_id`.
///
/// The id is generated by the column's `gen_random_uuid()` default, so this is a
/// plain `INSERT ... RETURNING` — not an upsert. (`authored_entities` upserts on
/// a *caller-supplied* stable `entity_id`; a scenario's id is server-minted with
/// no caller-stable business key, so there is no meaningful `ON CONFLICT`
/// target.) `status` is passed explicitly for a single clear code path; the
/// column's `'draft'` default remains a backstop for non-Rust inserts.
///
/// `direction` and `status` are validated by the table's CHECK constraints — an
/// out-of-set value surfaces here as a [`PipelineRepoError`] (a real failure,
/// never silently dropped).
///
/// # Errors
/// Returns [`PipelineRepoError`] if the insert fails — including a CHECK
/// violation on `direction`/`status`, or a NOT NULL violation on a required
/// column.
// Eight parameters (executor + seven insertable columns) trips
// `clippy::too_many_arguments`. Each carries a distinct, required column value;
// collapsing them into a params struct buys nothing here and would diverge from
// the sibling writers (`upsert_authored_entity`, `upsert_authored_relationship`)
// that carry the same allow for the same reason.
#[allow(clippy::too_many_arguments)]
pub async fn insert_scenario(
    executor: impl sqlx::PgExecutor<'_>,
    name: &str,
    direction: &str,
    status: &str,
    case_slug: &str,
    feeds_count_id: Option<&str>,
    anchor_allegation_ids: Option<&[String]>,
    definition: &serde_json::Value,
) -> Result<uuid::Uuid, PipelineRepoError> {
    let scenario_id = sqlx::query_scalar::<_, uuid::Uuid>(
        r#"INSERT INTO scenarios
               (name, direction, status, case_slug, feeds_count_id,
                anchor_allegation_ids, definition)
           VALUES ($1, $2, $3, $4, $5, $6, $7)
           RETURNING scenario_id"#,
    )
    .bind(name)
    .bind(direction)
    .bind(status)
    .bind(case_slug)
    .bind(feeds_count_id)
    // `Option<&[String]>` binds as a nullable text array: `None` → SQL NULL,
    // `Some(slice)` → the array literal.
    .bind(anchor_allegation_ids)
    .bind(definition)
    .fetch_one(executor)
    .await?;
    Ok(scenario_id)
}

/// Fetch one scenario by id. `None` if no such row exists.
///
/// # Errors
/// Returns [`PipelineRepoError`] if the query fails (connection/protocol/decode
/// error). A simply-absent row is `Ok(None)`, not an error.
pub async fn get_scenario(
    pool: &PgPool,
    scenario_id: uuid::Uuid,
) -> Result<Option<ScenarioRecord>, PipelineRepoError> {
    let sql = format!("SELECT {SCENARIO_COLUMNS} FROM scenarios WHERE scenario_id = $1");
    let row = sqlx::query_as::<_, ScenarioRecord>(&sql)
        .bind(scenario_id)
        .fetch_optional(pool)
        .await?;
    Ok(row)
}

/// List a case's scenarios, newest first.
///
/// # Errors
/// Returns [`PipelineRepoError`] if the query fails.
pub async fn list_scenarios_for_case(
    pool: &PgPool,
    case_slug: &str,
) -> Result<Vec<ScenarioRecord>, PipelineRepoError> {
    let sql = format!(
        "SELECT {SCENARIO_COLUMNS} FROM scenarios \
         WHERE case_slug = $1 ORDER BY created_at DESC, scenario_id"
    );
    let rows = sqlx::query_as::<_, ScenarioRecord>(&sql)
        .bind(case_slug)
        .fetch_all(pool)
        .await?;
    Ok(rows)
}

/// Delete every scenario for a case, returning the number of rows removed.
///
/// Present now for integration-test hygiene (re-runnable suites clear their own
/// rows); it is also the first slice of the eventual delete surface. Takes
/// `impl PgExecutor<'_>` for the same transaction-composability reason as
/// [`insert_scenario`].
///
/// # Errors
/// Returns [`PipelineRepoError`] if the delete fails.
pub async fn delete_scenarios_for_case(
    executor: impl sqlx::PgExecutor<'_>,
    case_slug: &str,
) -> Result<u64, PipelineRepoError> {
    let result = sqlx::query("DELETE FROM scenarios WHERE case_slug = $1")
        .bind(case_slug)
        .execute(executor)
        .await?;
    Ok(result.rows_affected())
}

/// Hard-delete ONE scenario, scoped by both its id AND its case. Returns the
/// number of rows removed (0 or 1).
///
/// ## Why the `case_slug` is in the WHERE clause, not checked afterwards
///
/// `scenario_id` is globally unique, so `WHERE scenario_id = $1` alone would
/// delete a row regardless of which case's URL reached it. Pinning the delete to
/// `scenario_id = $1 AND case_slug = $2` makes the case-isolation fence atomic:
/// a delete aimed through the wrong `:slug` matches zero rows and removes nothing,
/// so the caller cannot delete — nor even confirm the existence of — a scenario in
/// another case. This mirrors `update_scenario`'s fence exactly.
///
/// ## Rust Learning: `rows_affected()` vs `RETURNING` as the "did it delete?" signal
///
/// Two ways to know whether a `DELETE` hit a row. `RETURNING <cols>` sends the
/// deleted row back — useful only if the caller needs the row's data. Here the
/// caller just needs "0 or 1"; a `DELETE` with no `RETURNING` still reports how
/// many rows it touched via `result.rows_affected()`. So we take the cheaper
/// signal — no row is read back — and let the HANDLER turn `0` into a 404 and `1`
/// into a 204. This matches the same-module deletes (`delete_scenarios_for_case`,
/// `delete_fact_ref`), which all return `rows_affected()`.
///
/// The FK chain does the rest: `scenario_fact_refs` and `scenario_responses`
/// (and, below them, `response_items` → `response_item_fact_refs`) all declare
/// `ON DELETE CASCADE` back to `scenarios`, so deleting the row here takes its
/// curated facts and responses with it in the same statement — no manual cascade.
///
/// # Errors
/// Returns [`PipelineRepoError`] if the delete fails (a genuine store fault; a
/// no-such-row is NOT an error here — it is `Ok(0)`, which the handler maps to 404).
pub async fn delete_scenario(
    executor: impl sqlx::PgExecutor<'_>,
    scenario_id: uuid::Uuid,
    case_slug: &str,
) -> Result<u64, PipelineRepoError> {
    let result = sqlx::query("DELETE FROM scenarios WHERE scenario_id = $1 AND case_slug = $2")
        .bind(scenario_id)
        .bind(case_slug)
        .execute(executor)
        .await?;
    Ok(result.rows_affected())
}

/// Apply a partial update to one scenario and return the merged row.
///
/// ## The partial merge happens IN SQL, via `COALESCE`
///
/// Each mutable field is an `Option`: `Some(v)` writes `v`; `None` leaves the
/// column at its existing value. The merge is done by the database
/// (`COALESCE($n, column)`), NOT in Rust. `direction` is deliberately absent from
/// the SET list — offense/defense is a scenario's identity, not a mutable field
/// (mirrors `ScenarioUpdateRequest` omitting it).
///
/// ## Why this reads the row back with `RETURNING` (unlike `insert_scenario`)
///
/// `insert_scenario` can hand its caller a DTO built from the request values — it
/// wrote exactly those. An UPDATE cannot: a partial update leaves the
/// non-provided columns at their pre-existing DB values, which the caller does
/// not hold. So the `RETURNING {SCENARIO_COLUMNS}` row — decoded by the SAME
/// `query_as::<_, ScenarioRecord>` mechanism `get_scenario` uses — is the only
/// source of truth for the merged result, and this function returns the record
/// rather than `()`.
///
/// ## Two accepted B1 semantics (documented, NOT worked around)
///
/// - **`COALESCE` conflates "absent" with "null".** A `None` argument means
///   "field absent → keep existing"; there is therefore NO way through this
///   function to deliberately set `feeds_count_id` or `anchor_allegation_ids`
///   back to SQL NULL. Clearing a nullable field via `PUT` is unsupported in B1.
///   (Fixing it would need `Option<Option<T>>` or a presence sentinel — out of
///   scope.)
/// - **`definition` is a WHOLE-VALUE replace, not a deep merge.** A provided
///   `definition` overwrites the entire jsonb blob; it does not merge key-by-key
///   into the existing one. Correct for B1 — the typed `ScenarioDefinition` is
///   authored and replaced as one unit. (Row-level partial update + definition-
///   level whole replace is intentional, not a bug.)
///
/// The `WHERE scenario_id = $1 AND case_slug = $7` is the cross-case fence: an
/// update reached through the wrong case path matches zero rows (same discipline
/// the reads use), which surfaces as [`PipelineRepoError::NotFound`] — never a
/// silent no-op (Standing Rule 1).
///
/// # Errors
/// - [`PipelineRepoError::NotFound`] if no row matches `(scenario_id, case_slug)`
///   — a missing id OR a cross-case mismatch (indistinguishable by design, so
///   neither confirms the row exists under another case).
/// - [`PipelineRepoError`] (via the `From<sqlx::Error>` conversion) on any other
///   DB failure — including a CHECK violation if a bad `status` slips past the
///   handler's validation.
// Eight parameters (executor + scenario_id + the `case_slug` fence + five mutable
// fields) trips `clippy::too_many_arguments`, exactly as `insert_scenario` does.
// Each is a distinct required value; a params struct buys nothing and would
// diverge from the sibling writer, so we carry the same allow for the same reason.
#[allow(clippy::too_many_arguments)]
pub async fn update_scenario(
    executor: impl sqlx::PgExecutor<'_>,
    scenario_id: uuid::Uuid,
    case_slug: &str,
    name: Option<&str>,
    status: Option<&str>,
    feeds_count_id: Option<&str>,
    anchor_allegation_ids: Option<&[String]>,
    definition: Option<&serde_json::Value>,
) -> Result<ScenarioRecord, PipelineRepoError> {
    // RETURNING reuses the shared projection so the read-back can never drift
    // from `get_scenario`'s column set. `updated_at` is already in
    // `SCENARIO_COLUMNS`, so it is NOT re-listed here.
    let sql = format!(
        "UPDATE scenarios SET \
             name                  = COALESCE($2, name), \
             status                = COALESCE($3, status), \
             feeds_count_id        = COALESCE($4, feeds_count_id), \
             anchor_allegation_ids = COALESCE($5, anchor_allegation_ids), \
             definition            = COALESCE($6, definition), \
             updated_at            = now() \
         WHERE scenario_id = $1 AND case_slug = $7 \
         RETURNING {SCENARIO_COLUMNS}"
    );

    // Bind order matches $1..$7 above. A `None` binds as SQL NULL, so the
    // corresponding `COALESCE` keeps the column's existing value.
    let row = sqlx::query_as::<_, ScenarioRecord>(&sql)
        .bind(scenario_id)
        .bind(name)
        .bind(status)
        .bind(feeds_count_id)
        .bind(anchor_allegation_ids)
        .bind(definition)
        .bind(case_slug)
        .fetch_optional(executor)
        .await?;

    // Zero rows ⇒ no scenario with that id in that case. Loud, specific NotFound —
    // never a silent success. Mirrors the `authored_entities` update precedent.
    row.ok_or_else(|| PipelineRepoError::NotFound(scenario_id.to_string()))
}

// ── scenario_fact_refs (task 1.2) ────────────────────────────────

/// A row from `scenario_fact_refs` — one graph fact's reference into one
/// scenario, with the role it plays *there*.
///
/// ## Rust Learning: composite-key identity, no surrogate id
///
/// Unlike [`ScenarioRecord`] (whose identity is a server-minted `scenario_id`
/// uuid), a fact reference's identity *is* its business key — the pair
/// `(scenario_id, graph_node_id)`, which is the table's composite PRIMARY KEY.
/// There is no surrogate `id` column and no `id` field here: the caller always
/// already holds both halves of the key, so there is nothing for the database to
/// mint and return. That is why [`upsert_fact_ref`] returns `()` rather than an
/// id (contrast [`insert_scenario`], which returns the uuid the DB generated).
///
/// Holds NO case content: `graph_node_id` is a pointer into Neo4j; the fact's
/// quote/speaker/citation are read live from the graph at compose time.
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ScenarioFactRefRecord {
    pub scenario_id: uuid::Uuid,
    pub graph_node_id: String,
    pub role_in_this_scenario: Option<String>,
    pub confirmed: bool,
    pub note: Option<String>,
    pub tagged_at: chrono::DateTime<chrono::Utc>,
}

// CONST: column projection locked to the `scenario_fact_refs` schema — a
// structural schema-coupling invariant, NOT a deployment-time config value (same
// rationale as `SCENARIO_COLUMNS`). Changing it requires a migration plus a
// matching `ScenarioFactRefRecord` field update.
const SCENARIO_FACT_REF_COLUMNS: &str =
    "scenario_id, graph_node_id, role_in_this_scenario, confirmed, note, tagged_at";

/// Tag a graph fact into a scenario, or re-tag it in place (composite-key
/// upsert on `(scenario_id, graph_node_id)`).
///
/// Re-tagging the same pair is a normal edit, not an error: `ON CONFLICT
/// (scenario_id, graph_node_id) DO UPDATE` overwrites the role / confirmed /
/// note and advances `tagged_at`. The SAME `graph_node_id` under a *different*
/// `scenario_id` is a *different* row — that is how one fact is shared across
/// scenarios with a per-scenario role.
///
/// Returns `()`: the caller already holds the identity (the composite key), so
/// nothing is server-minted to hand back (contrast [`insert_scenario`]).
///
/// `role_in_this_scenario` is intentionally unvalidated here — the role
/// vocabulary is owned by the task-1.3 code lookup; this layer stores whatever
/// the validated caller passes (or `None`).
///
/// ## Rust Learning: `Option<f32>` ↔ SQL `NULL`, and why `f32`
///
/// `confidence: Option<f32>` is the type-level statement "this value may be
/// absent." sqlx maps `Option<T>` to SQL automatically: `Some(0.9)` binds the
/// float `0.9`; `None` binds `NULL`. So the human-path callers that pass `None`
/// are not using a placeholder — `None` IS the correct, permanent semantics: a
/// hand-curated fact has no *model* confidence, so its column is genuinely NULL.
/// Only the Theme Scan (D2b) writes `Some(_)`.
///
/// `f32` (SQL `REAL`) not `f64` (`DOUBLE PRECISION`): the model emits a
/// ~2-decimal confidence in `[0.0, 1.0]`; `REAL`'s ~7 significant digits is
/// ample and the column is half the width. A deliberate width choice, matched
/// to the `REAL` column added by the 2026-07-06 migration.
///
/// # Errors
/// Returns [`PipelineRepoError`] if the write fails — notably a foreign-key
/// violation if `scenario_id` names no existing scenario.
pub async fn upsert_fact_ref(
    executor: impl sqlx::PgExecutor<'_>,
    scenario_id: uuid::Uuid,
    graph_node_id: &str,
    role_in_this_scenario: Option<&str>,
    confirmed: bool,
    note: Option<&str>,
    confidence: Option<f32>,
) -> Result<(), PipelineRepoError> {
    sqlx::query(
        r#"INSERT INTO scenario_fact_refs
               (scenario_id, graph_node_id, role_in_this_scenario, confirmed, note, confidence)
           VALUES ($1, $2, $3, $4, $5, $6)
           ON CONFLICT (scenario_id, graph_node_id) DO UPDATE SET
               role_in_this_scenario = EXCLUDED.role_in_this_scenario,
               confirmed             = EXCLUDED.confirmed,
               note                  = EXCLUDED.note,
               confidence            = EXCLUDED.confidence,
               tagged_at             = NOW()"#,
    )
    .bind(scenario_id)
    .bind(graph_node_id)
    .bind(role_in_this_scenario)
    .bind(confirmed)
    .bind(note)
    .bind(confidence)
    .execute(executor)
    .await?;
    Ok(())
}

/// List every fact reference for one scenario, oldest tag first.
///
/// The composite PK's leading column (`scenario_id`) serves this `WHERE`, so no
/// separate index is needed.
///
/// # Errors
/// Returns [`PipelineRepoError`] if the query fails.
pub async fn list_fact_refs_for_scenario(
    pool: &PgPool,
    scenario_id: uuid::Uuid,
) -> Result<Vec<ScenarioFactRefRecord>, PipelineRepoError> {
    let sql = format!(
        "SELECT {SCENARIO_FACT_REF_COLUMNS} FROM scenario_fact_refs \
         WHERE scenario_id = $1 ORDER BY tagged_at, graph_node_id"
    );
    let rows = sqlx::query_as::<_, ScenarioFactRefRecord>(&sql)
        .bind(scenario_id)
        .fetch_all(pool)
        .await?;
    Ok(rows)
}

/// Remove one fact reference from a scenario by its composite key.
///
/// Returns the number of rows deleted: `1` when the `(scenario_id,
/// graph_node_id)` pair existed, `0` when it did not. The handler turns a `0`
/// into a `404` (nothing to remove) and a `1` into a `204` — so "removed" and
/// "was never there" stay distinct observables (Standing Rule 1), rather than
/// both collapsing into a silent success.
///
/// Mirrors [`delete_scenarios_for_case`]'s shape (executor-generic, returns
/// `rows_affected()`); the only difference is the composite-key `WHERE`.
///
/// # Errors
/// Returns [`PipelineRepoError`] if the delete fails.
pub async fn delete_fact_ref(
    executor: impl sqlx::PgExecutor<'_>,
    scenario_id: uuid::Uuid,
    graph_node_id: &str,
) -> Result<u64, PipelineRepoError> {
    let result =
        sqlx::query("DELETE FROM scenario_fact_refs WHERE scenario_id = $1 AND graph_node_id = $2")
            .bind(scenario_id)
            .bind(graph_node_id)
            .execute(executor)
            .await?;
    Ok(result.rows_affected())
}

// ── Tests ────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    /// Read a pipeline migration file by name from disk.
    fn read_migration(filename: &str) -> String {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("pipeline_migrations")
            .join(filename);
        std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read migration {}: {e}", path.display()))
    }

    /// Compile-only guard on `update_scenario`'s signature.
    ///
    /// This function is NEVER invoked (`#[allow(dead_code)]`) — it exists purely
    /// so the compiler type-checks the exact argument list B1 depends on:
    /// executor-generic (a `&PgPool` satisfies the bound), the cross-case
    /// `case_slug` fence, the five `Option`-wrapped mutable fields in their
    /// COALESCE bind order, and the `Result<ScenarioRecord, PipelineRepoError>`
    /// return. A drift in the parameter list — which would silently break the
    /// bind order or drop the fence — fails the build HERE rather than at a far
    /// call site. The module's other tests are filesystem migration-scans that
    /// cannot exercise live SQL, so this compile check is the store-layer
    /// discipline for a function whose real behavior lives in the `--ignored`
    /// integration suite.
    #[allow(dead_code)]
    async fn update_scenario_signature_is_stable(pool: &sqlx::PgPool) {
        // Named binding with an explicit type asserts the return shape; the
        // leading underscore suppresses the unused-variable warning. This is a
        // typed binding, NOT a `let _ = ` Result discard (Standing Rule 1).
        let _result: Result<super::ScenarioRecord, super::PipelineRepoError> =
            super::update_scenario(
                pool,
                uuid::Uuid::nil(),
                "awad_v_catholic_family_service",
                Some("Marie is obstructive"),
                Some("draft"),
                Some("count-1"),
                Some(&["allegation-1".to_string()][..]),
                Some(&serde_json::json!({ "attack_text": "x", "schema_v": 1 })),
            )
            .await;
    }

    /// True if `line` (already trimmed + lowercased) is a column-definition line
    /// within a `CREATE TABLE` body — i.e. it names one of the SQL types these
    /// tables use and is not a `--` comment / PRIMARY KEY / CONSTRAINT / CHECK
    /// clause. `" integer"` is included so `item_index INTEGER` is recognized.
    fn is_column_line(lower: &str) -> bool {
        !lower.starts_with("--")
            && !lower.starts_with("primary key")
            && !lower.starts_with("constraint")
            && !lower.starts_with("check")
            && (lower.contains(" text")
                || lower.contains(" uuid")
                || lower.contains(" jsonb")
                || lower.contains(" boolean")
                || lower.contains(" integer")
                || lower.contains(" timestamptz")
                || lower.contains("text["))
    }

    /// Rule 21 disk/code invariant, shared by every scenario-family migration
    /// scan: assert a migration's column-DEFINITION lines (a) contain no
    /// case-content token and (b) include every expected column.
    ///
    /// Scans the migration text rather than a live DB so it runs in CI (no
    /// database needed), mirroring the canonical-loader filesystem-scan tests.
    /// Handles a migration that declares MULTIPLE tables: it walks EVERY
    /// `CREATE TABLE ( ... )` block and unions their column lines. Bounding to
    /// the table bodies means the multi-line `COMMENT ON` prose (which
    /// deliberately *says* "quotes, citations, or facts" to document the
    /// prohibition) can never be mistaken for a column.
    fn assert_no_case_content(sql: &str, sanity_col: &str, expected: &[&str]) {
        let mut column_lines: Vec<&str> = Vec::new();
        let mut rest = sql;
        while let Some(start) = rest.find("CREATE TABLE") {
            let after = &rest[start..];
            let end = after.find(");").expect("CREATE TABLE block closed with );");
            let body = &after[..end];
            for line in body.lines().map(str::trim) {
                if is_column_line(&line.to_ascii_lowercase()) {
                    column_lines.push(line);
                }
            }
            // Advance past this block's closer so the next iteration finds the
            // next CREATE TABLE (COMMENT prose between tables is skipped — it is
            // outside any table body).
            rest = &after[end + 2..];
        }

        // Sanity: we actually located at least one column block.
        assert!(
            column_lines.iter().any(|l| l.starts_with(sanity_col)),
            "column-line filter failed to find {sanity_col}; lines: {column_lines:?}"
        );

        const FORBIDDEN: [&str; 6] = [
            "quote",
            "verbatim",
            "citation",
            "fact_text",
            "source_document",
            "grounding",
        ];
        for line in &column_lines {
            let lower = line.to_ascii_lowercase();
            for token in FORBIDDEN {
                assert!(
                    !lower.contains(token),
                    "table must hold NO case content — forbidden token '{token}' \
                     in column line: {line}"
                );
            }
        }

        for col in expected {
            assert!(
                column_lines.iter().any(|l| l.starts_with(col)),
                "expected column '{col}' missing from migration"
            );
        }
    }

    /// Rule 21 (scenarios): the table must never grow a case-content column —
    /// quotes/citations/facts live in the graph (referenced by
    /// `scenario_fact_refs`), never here.
    #[test]
    fn scenarios_migration_declares_no_case_content_columns() {
        let sql = read_migration("20260626115557_create_scenarios_table.sql");
        assert_no_case_content(
            &sql,
            "scenario_id",
            &[
                "scenario_id",
                "name",
                "direction",
                "status",
                "case_slug",
                "feeds_count_id",
                "anchor_allegation_ids",
                "definition",
                "created_at",
                "updated_at",
            ],
        );
    }

    /// Rule 21 (scenario_fact_refs): the reference table must never grow a
    /// case-content column — facts are read live from the graph by id, never
    /// stored here.
    #[test]
    fn fact_refs_migration_declares_no_case_content_columns() {
        let sql = read_migration("20260626122424_create_scenario_fact_refs_table.sql");
        assert_no_case_content(
            &sql,
            "scenario_id",
            &[
                "scenario_id",
                "graph_node_id",
                "role_in_this_scenario",
                "confirmed",
                "note",
                "tagged_at",
            ],
        );
    }

    /// Rule 21 (scenario responses, 1.6): the three response tables must never
    /// grow a case-content column — evidence is referenced by graph node id and
    /// read live from the graph, never stored. This migration declares THREE
    /// tables in one file, exercising the multi-block scan.
    #[test]
    fn responses_migration_declares_no_case_content_columns() {
        let sql = read_migration("20260626135022_create_scenario_responses_tables.sql");
        assert_no_case_content(
            &sql,
            "scenario_id",
            &[
                // scenario_responses
                "scenario_id",
                "label",
                "status",
                "origin",
                "updated_at",
                // response_items
                "response_id",
                "item_index",
                // response_item_fact_refs
                "response_item_id",
                "graph_node_id",
                "note",
                "tagged_at",
                // shared across tables (id / text / created_at)
                "id",
                "text",
                "created_at",
            ],
        );
    }
}
