//! Scenario authored-state store (task 1.1).
//!
//! Owns CRUD for the `scenarios` table created by migration
//! `20260626115557_create_scenarios_table.sql` (in `colossus_legal_v2`, the
//! pipeline database). A scenario is a saved **lens** over the case graph: this
//! table stores only its authored *definition* plus the spine columns the system
//! filters and joins on. It holds **no case content** — no quotes, citations, or
//! facts. Those live in the graph and are referenced by `scenario_fact_refs`
//! (task 1.2), not here.
//!
//! ## Why this is `scenario_store`, not a `ScenarioRepository`
//!
//! A `ScenarioRepository` already exists — the task 0.3 Neo4j graph reader
//! (`repositories::scenario_repository`). To avoid colliding with it, this
//! Postgres authored-state code mirrors the house precedent's shape exactly:
//! stateless free functions (like `authored_entities`), not a struct. Mutators
//! take `impl sqlx::PgExecutor<'_>` so a caller can enroll them in a
//! transaction; readers take `&PgPool`.
//!
//! ## Rust Learning: `impl sqlx::PgExecutor<'_>` on mutators
//!
//! Taking `impl PgExecutor<'_>` (rather than `&PgPool`) means the same function
//! works whether the caller passes a `&PgPool` (each call its own
//! auto-committed statement) or a `&mut Transaction` (several calls in one
//! all-or-nothing unit). A `&PgPool` satisfies the bound, so simple call sites
//! pass `&pool` unchanged — the flexibility costs the caller nothing. The read
//! helpers keep `&PgPool` because there is no transaction-composition need on a
//! plain SELECT.

use sqlx::PgPool;

use super::PipelineRepoError;

// ── Record type ──────────────────────────────────────────────────

/// A row from `scenarios`.
///
/// Field names match the columns exactly so `#[derive(sqlx::FromRow)]` maps the
/// row without a manual decoder.
///
/// ## Rust Learning: `TEXT[]` → `Option<Vec<String>>`
///
/// `anchor_allegation_ids` is a nullable Postgres text array. sqlx decodes a
/// SQL array to a `Vec<T>`, and a nullable column to `Option<…>`, so the column
/// type is `Option<Vec<String>>`: `None` for SQL `NULL`, `Some(vec![])` for an
/// empty array, `Some(vec![..])` for a populated one — three distinguishable
/// states (Standing Rule 1).
///
/// ## Why `definition` is `serde_json::Value`, not a typed struct
///
/// The definition body (attack_text, wielders, seed phrases, a `schema_v` tag,
/// …) is the authored part that churns. Modeling it as a Rust struct would force
/// a recompile — and often a migration — on every authoring-format tweak. As
/// raw `serde_json::Value` it absorbs change freely; its shape is validated at
/// render time (task 1.5), not by this store or the table. This mirrors how
/// `authored_entities.item_data` is stored.
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ScenarioRecord {
    pub scenario_id: uuid::Uuid,
    pub name: String,
    pub direction: String,
    pub status: String,
    pub case_slug: String,
    pub feeds_count_id: Option<String>,
    pub anchor_allegation_ids: Option<Vec<String>>,
    pub definition: serde_json::Value,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

/// Shared SELECT projection for every `ScenarioRecord` read, so the `FromRow`
/// column set can never drift between query sites (the house anti-drift
/// discipline; see `authored_entities::ENTITY_COLUMNS`).
// CONST: column projection locked to the `scenarios` schema. This is a
// structural schema-coupling invariant, NOT a deployment-time config value —
// changing it requires a simultaneous migration and a matching `ScenarioRecord`
// field update, so it cannot live in YAML/env (Standing Rule 2 does not apply).
const SCENARIO_COLUMNS: &str = "scenario_id, name, direction, status, case_slug, \
     feeds_count_id, anchor_allegation_ids, definition, created_at, updated_at";

// ── CRUD ─────────────────────────────────────────────────────────

/// Insert a scenario and return its database-minted `scenario_id`.
///
/// The id is generated by the column's `gen_random_uuid()` default, so this is a
/// plain `INSERT ... RETURNING` — not an upsert. (`authored_entities` upserts on
/// a *caller-supplied* stable `entity_id`; a scenario's id is server-minted with
/// no caller-stable business key, so there is no meaningful `ON CONFLICT`
/// target.) `status` is passed explicitly for a single clear code path; the
/// column's `'draft'` default remains a backstop for non-Rust inserts.
///
/// `direction` and `status` are validated by the table's CHECK constraints — an
/// out-of-set value surfaces here as a [`PipelineRepoError`] (a real failure,
/// never silently dropped).
///
/// # Errors
/// Returns [`PipelineRepoError`] if the insert fails — including a CHECK
/// violation on `direction`/`status`, or a NOT NULL violation on a required
/// column.
// Eight parameters (executor + seven insertable columns) trips
// `clippy::too_many_arguments`. Each carries a distinct, required column value;
// collapsing them into a params struct buys nothing here and would diverge from
// the sibling writers (`upsert_authored_entity`, `upsert_authored_relationship`)
// that carry the same allow for the same reason.
#[allow(clippy::too_many_arguments)]
pub async fn insert_scenario(
    executor: impl sqlx::PgExecutor<'_>,
    name: &str,
    direction: &str,
    status: &str,
    case_slug: &str,
    feeds_count_id: Option<&str>,
    anchor_allegation_ids: Option<&[String]>,
    definition: &serde_json::Value,
) -> Result<uuid::Uuid, PipelineRepoError> {
    let scenario_id = sqlx::query_scalar::<_, uuid::Uuid>(
        r#"INSERT INTO scenarios
               (name, direction, status, case_slug, feeds_count_id,
                anchor_allegation_ids, definition)
           VALUES ($1, $2, $3, $4, $5, $6, $7)
           RETURNING scenario_id"#,
    )
    .bind(name)
    .bind(direction)
    .bind(status)
    .bind(case_slug)
    .bind(feeds_count_id)
    // `Option<&[String]>` binds as a nullable text array: `None` → SQL NULL,
    // `Some(slice)` → the array literal.
    .bind(anchor_allegation_ids)
    .bind(definition)
    .fetch_one(executor)
    .await?;
    Ok(scenario_id)
}

/// Fetch one scenario by id. `None` if no such row exists.
///
/// # Errors
/// Returns [`PipelineRepoError`] if the query fails (connection/protocol/decode
/// error). A simply-absent row is `Ok(None)`, not an error.
pub async fn get_scenario(
    pool: &PgPool,
    scenario_id: uuid::Uuid,
) -> Result<Option<ScenarioRecord>, PipelineRepoError> {
    let sql = format!("SELECT {SCENARIO_COLUMNS} FROM scenarios WHERE scenario_id = $1");
    let row = sqlx::query_as::<_, ScenarioRecord>(&sql)
        .bind(scenario_id)
        .fetch_optional(pool)
        .await?;
    Ok(row)
}

/// List a case's scenarios, newest first.
///
/// # Errors
/// Returns [`PipelineRepoError`] if the query fails.
pub async fn list_scenarios_for_case(
    pool: &PgPool,
    case_slug: &str,
) -> Result<Vec<ScenarioRecord>, PipelineRepoError> {
    let sql = format!(
        "SELECT {SCENARIO_COLUMNS} FROM scenarios \
         WHERE case_slug = $1 ORDER BY created_at DESC, scenario_id"
    );
    let rows = sqlx::query_as::<_, ScenarioRecord>(&sql)
        .bind(case_slug)
        .fetch_all(pool)
        .await?;
    Ok(rows)
}

/// Delete every scenario for a case, returning the number of rows removed.
///
/// Present now for integration-test hygiene (re-runnable suites clear their own
/// rows); it is also the first slice of the eventual delete surface. Takes
/// `impl PgExecutor<'_>` for the same transaction-composability reason as
/// [`insert_scenario`].
///
/// # Errors
/// Returns [`PipelineRepoError`] if the delete fails.
pub async fn delete_scenarios_for_case(
    executor: impl sqlx::PgExecutor<'_>,
    case_slug: &str,
) -> Result<u64, PipelineRepoError> {
    let result = sqlx::query("DELETE FROM scenarios WHERE case_slug = $1")
        .bind(case_slug)
        .execute(executor)
        .await?;
    Ok(result.rows_affected())
}

// ── Tests ────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    /// Path to the scenarios migration on disk.
    fn migration_sql() -> String {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("pipeline_migrations")
            .join("20260626115557_create_scenarios_table.sql");
        std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read migration {}: {e}", path.display()))
    }

    /// Rule 21 disk/code invariant: the `scenarios` table must never grow a
    /// case-content column. Quotes, citations, and facts live in the graph
    /// (referenced by `scenario_fact_refs`, task 1.2), never in this table.
    ///
    /// This scans the migration text rather than the live DB so it runs in CI
    /// (no database needed), mirroring the canonical-loader filesystem-scan
    /// tests. The COMMENTs deliberately *say* "quotes, citations, or facts" to
    /// document the prohibition, so we only forbid these tokens in column
    /// *definition* lines — identified by the leading whitespace + identifier +
    /// type shape — not anywhere in the file.
    #[test]
    fn migration_declares_no_case_content_columns() {
        let sql = migration_sql();

        // Column-definition lines look like `    <name>  <TYPE>...`. COMMENT
        // and CONSTRAINT lines do not start a bare identifier followed by a SQL
        // type, so this isolates the actual columns.
        let column_lines: Vec<&str> = sql
            .lines()
            .map(str::trim)
            .filter(|l| {
                let lower = l.to_ascii_lowercase();
                // Heuristic: a column line names one of the SQL types this table
                // uses and is not a COMMENT/CONSTRAINT/CHECK line.
                !lower.starts_with("comment")
                    && !lower.starts_with("constraint")
                    && !lower.starts_with("check")
                    && (lower.contains(" text")
                        || lower.contains(" uuid")
                        || lower.contains(" jsonb")
                        || lower.contains(" timestamptz")
                        || lower.contains("text["))
            })
            .collect();

        // Sanity: we actually located the column block.
        assert!(
            column_lines.iter().any(|l| l.starts_with("scenario_id")),
            "column-line filter failed to find scenario_id; lines: {column_lines:?}"
        );

        const FORBIDDEN: [&str; 6] = [
            "quote",
            "verbatim",
            "citation",
            "fact_text",
            "source_document",
            "grounding",
        ];
        for line in &column_lines {
            let lower = line.to_ascii_lowercase();
            for token in FORBIDDEN {
                assert!(
                    !lower.contains(token),
                    "scenarios must hold NO case content — forbidden token '{token}' \
                     in column line: {line}"
                );
            }
        }

        // And the expected spine + definition columns are all present.
        const EXPECTED: [&str; 10] = [
            "scenario_id",
            "name",
            "direction",
            "status",
            "case_slug",
            "feeds_count_id",
            "anchor_allegation_ids",
            "definition",
            "created_at",
            "updated_at",
        ];
        for col in EXPECTED {
            assert!(
                column_lines.iter().any(|l| l.starts_with(col)),
                "expected column '{col}' missing from migration"
            );
        }
    }
}
